AdvertismentSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import static

from AdvertismentSite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('advertisement/', include('advertisement.urls', namespace='advertisement')),

    path('accounts/', include('user.urls', namespace='accounts')),
    path('captcha/', include('captcha.urls')),
]+static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertisement/urls.py
from django.urls import path

from advertisement.views import \
    AdvertisementDetail, AdvertisementAddView,\
    profile_adv_update, profile_adv_delete,\
    by_rubric, detail, by_main_page

app_name = 'advertisement'

urlpatterns = [
    path('', by_main_page, name='advertisement_list'),
    path('<int:pk>/', AdvertisementDetail.as_view(), name='advertisement_detail'),
    path('rubric/<int:pk>/', by_rubric, name='rubric'),
    path('rubric/info/<int:pk>/', detail, name='detail'),
    path('profile/add/', AdvertisementAddView.as_view(), name='add_adv'),
    path('profile/update/<int:pk>/', profile_adv_update, name='update'),
    path('profile/delete/<int:pk>/', profile_adv_delete, name='delete' )
]

user/urls.py
from django.urls import path

from user.views import SignIn, LogOut,\
    SignUp, user_activate_by_email,\
    ChangeUserInfoView, profile,\
    PasswordChange

app_name = 'accounts'
urlpatterns = [
    path('sign_in/', SignIn.as_view(), name='sign_in'),
    path('log_out/', LogOut.as_view(), name='log_out'),
    path('sign_up/', SignUp.as_view(), name='register'),
    path('user/profile/', profile, name='profile'),
    path('user/activate/<str:sign>/', user_activate_by_email, name='register_activate'),
    path('user/change/', ChangeUserInfoView.as_view(), name='change_info'),
    path('user/password/change/', PasswordChange.as_view(), name='password_change')
]

templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head >
    <meta charset="UTF-8" >
    <meta http-equiv="Content-Type"
    content="text/html; charset=utf-8">
    <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    rel="stylesheet"
    crossorigin="anonymous">
    <title >
        {% block title %}Advertisement Site{% endblock %}
    </title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css"
    href="{% static 'main.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head >
<body class="container-fluid">
    <header class="mb-4">
    <h1 class="display-1 tехt-сеntеr">Advertising</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}"> Sign up</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                   role="button" aria-haspopup="true" aria-expanded="false"> Profile </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'accounts:profile' %}">My adv </a>
                    <a class="dropdown-item" href="{% url 'accounts:change_info' %}">Change info about me</a>
                    <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change password</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'accounts:log_out' %}">Log out</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Delete</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item"><a class="nav-link"
                    href="{% url 'accounts:sign_in' %}">Sign in</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto nav flex-column border">
            <a class="nav-link root"
               href="{% url 'advertisement:advertisement_list' %}">Main Page</a>
            {% for rubric in rubrics %}
                {% ifchanged rubric.super_rubric.pk %}
                    <span class="nav-link root font-weight-bold">
                    {{ rubric.super_rubric.name }}</span>
                {% endifchanged %}
                <a class="nav-link" href="{% url 'advertisement:rubric' pk=rubric.pk %}">
                {{ rubric.name }}
                </a>
            {% endfor %}
        </nav>
        <section class="col border ру-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">
            &copy;2020
        </p>
    </footer>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block seacrhform %}
{% endblock %}

{% block content %}
   {% include 'macro.html' %}
{% endblock %}

templates/macro.html
{% load thumbnail %}
{% load bootstrap4 %}
{% load static %}

<div class="container-fluid mb-2">
    <div class="row">
        <div class="col">&nbsp;</div>
        <form class="col-md-auto form-inline">
            {% bootstrap_form form show_label=False %}
            {% bootstrap_button content='Find' button_type='submit' %}
        </form>
    </div>
</div>
{% if advertisements %}
    <ul class="list-unstyled">
        {% for adv in advertisements %}
            <li class="media mb-2 p-3 border">
                {% url 'advertisement:detail' pk=adv.pk as url%}
                <a href="{{ url }}{{ all }}">
                    {% if adv.image %}
                        <img class="mr-3" src="{% thumbnail adv.image 'default' %}">
                        {% else %}
                        <img class="mr-3" src="{% static 'white-image.png' %}" style="width:96px;height:96px;">

                    {% endif %}
                </a>
            <div class="media-body">
                <h3><a href="{{ url }}{{ all }}">
                    {{ adv.title }}
                </a></h3>
                <div>{{ adv.content }}</div>
                <p class="text-right font-weight-bold">
                    {{ adv.price }}
                </p>
                <p class="text-right font-italic">{{ adv.created_at }}</p>
            </div>
            </li>
        {% endfor %}
    </ul>
    {% bootstrap_pagination page url=keyword%}
{% endif %}